# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='is_recipe',
            field=models.BooleanField(default=False),
        ),
    ]
