# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 22:50
from __future__ import unicode_literals

import blog.blogstreamblock
import blog.video
from django.db import migrations, models
import django.db.models.deletion
import twosapearWagtail.blocks.imagealignmentchoiceblock
import twosapearWagtail.blocks.imageformatchoiceblock
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('blog', '0002_blogpage_is_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_url', models.URLField(blank=True, verbose_name='Embed URL')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', twosapearWagtail.blocks.imagealignmentchoiceblock.ImageAlignmentChoiceBlock())), icon='image', label='Aligned image')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock('quote title')), ('attribution', wagtail.wagtailcore.blocks.CharBlock())))), ('aligned_html', wagtail.wagtailcore.blocks.StructBlock((('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('alignment', blog.blogstreamblock.HTMLAlignmentChoiceBlock())), icon='code', label='Raw HTML')), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse')), ('timed_image_series', wagtail.wagtailcore.blocks.StructBlock((('id', wagtail.wagtailcore.blocks.CharBlock(default='01', label='ID MUST BE UNIQUE')), ('images', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image', label='Image'))), ('width', wagtail.wagtailcore.blocks.CharBlock(label='Image Width')), ('height', wagtail.wagtailcore.blocks.CharBlock(label='Image Height')), ('interval', wagtail.wagtailcore.blocks.CharBlock(label='Interval in seconds')), ('format', twosapearWagtail.blocks.imageformatchoiceblock.ImageFormatChoiceBlock(default='square_md', label='Image Base Format')), ('alignment', twosapearWagtail.blocks.imagealignmentchoiceblock.ImageAlignmentChoiceBlock())), icon='image', label='Timed images for my babyo :)', template='blog/timedimageseries.html')), ('video_embed', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(blog.video.Video)))),
        ),
    ]
