# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160410_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='thug', max_length=40),
            preserve_default=False,
        ),
    ]
