# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0004_capitalizeverbose'),
        ('blog', '0005_blogpagecarouselitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexrelatedlink',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
