# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160411_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('serving_size_quantity', models.DecimalField(blank=True, decimal_places=1, max_digits=10)),
                ('serving_size_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=10)),
                ('serving_size_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=10)),
                ('serving_quantity_description', models.CharField(blank=True, max_length=100, unique=True)),
                ('calories', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('calories_from_fat', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('total_fat', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('sat_fat', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('poly_unsat_fat', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('mono_unsat_fat', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('cholesterol', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('sodium', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('potassium', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('carbs', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('fiber', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('sugar', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('vitamin_a', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('vitamin_c', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('calcium', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('iron', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
            ],
        ),
    ]
