# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 04:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateField(default=datetime.date(2016, 4, 16)),
        ),
        migrations.AddField(
            model_name='video',
            name='show_video',
            field=models.BooleanField(default=True),
        ),
    ]
