# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160319_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='feed_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='feed_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
