# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 03:57
from __future__ import unicode_literals

import blog.blogstreamblock
from django.db import migrations, models
import django.db.models.deletion
import twosapearWagtail.blocks.imagealignmentchoiceblock
import twosapearWagtail.blocks.imageformatchoiceblock
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', twosapearWagtail.blocks.imagealignmentchoiceblock.ImageAlignmentChoiceBlock())), icon='image', label='Aligned image')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock('quote title')), ('attribution', wagtail.wagtailcore.blocks.CharBlock())))), ('aligned_html', wagtail.wagtailcore.blocks.StructBlock((('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('alignment', blog.blogstreamblock.HTMLAlignmentChoiceBlock())), icon='code', label='Raw HTML')), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse')), ('timed_image_series', wagtail.wagtailcore.blocks.StructBlock((('id', wagtail.wagtailcore.blocks.CharBlock(default='01', label='ID MUST BE UNIQUE')), ('images', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image', label='Image'))), ('width', wagtail.wagtailcore.blocks.CharBlock(label='Image Width')), ('height', wagtail.wagtailcore.blocks.CharBlock(label='Image Height')), ('interval', wagtail.wagtailcore.blocks.CharBlock(label='Interval in seconds')), ('format', twosapearWagtail.blocks.imageformatchoiceblock.ImageFormatChoiceBlock(default='square_md', label='Image Base Format')), ('alignment', twosapearWagtail.blocks.imagealignmentchoiceblock.ImageAlignmentChoiceBlock())), icon='image', label='Timed images for my babyo :)', template='blog/timedimageseries.html'))), blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
